Fixed bugs connected with mentions
warsztatywww/TosterBot pull request #27
Opened 2020-07-08 18:35 UTC by Skelu21

2020-07-08 19:31 UTC, krzys-h requested changes

2020-07-08 19:31 UTC, krzys-h commented on toster.py
> -            print(f"file {backup_file} doesn't exist: initializing new backup")
why? I wanted these messages, you were supposed to remove your print only :P

2020-07-08 19:52 UTC, Skelu21 commented on toster.py
> -            print(f"file {backup_file} doesn't exist: initializing new backup")
Ok, sorry. I wasn't sure but thought you can just undelete these lines in case you want them

2020-07-08 19:53 UTC, krzys-h commented on toster.py
> -            print(f"file {backup_file} doesn't exist: initializing new backup")
just fix it in the pull request please ;)

2020-07-09 06:53 UTC, krzys-h approved these changes

2020-07-09 06:53 UTC, merged